###################################################
# Docker Compose for Oil Price Prediction Application
#
# Simplified version without Traefik proxy
# All services accessible directly via their ports
###################################################

services:

  ###################################################
  # Service: backend
  #
  # FastAPI server for the prediction API
  ###################################################
  backend:
    build:
      context: ./
      target: backend-dev
    ports:
      - "8000:8000"
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    depends_on:
      - qdrant
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - __pycache__
            - '*.pyc'
            - .pytest_cache
        - path: ./backend/requirements.txt
          action: rebuild

  ###################################################
  # Service: client
  #
  # React + Vite frontend application
  ###################################################
  client:
    build:
      context: ./
      target: client-dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: /usr/local/app/src
        - path: ./client/package.json
          action: rebuild

  ###################################################
  # Service: qdrant
  #
  # Vector database for similarity search
  ###################################################
  qdrant:
    image: qdrant/qdrant:v1.12.0
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - oil-price-qdrant-data:/qdrant/storage

  ###################################################
  # Service: qdrant-web-ui
  #
  # Web interface for Qdrant management
  ###################################################
  qdrant-web-ui:
    image: qdrant/qdrant:v1.12.0
    command: ["./qdrant", "--ui-path", "/"]
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - 6335:6333
    volumes:
      - oil-price-qdrant-data:/qdrant/storage

###################################################
# Volumes
###################################################
volumes:
  oil-price-qdrant-data:
